### ISSUE TITLE
socket.error: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by manyunya** [p4u/stratum-relay#1]
[1420777421][error][pxy87488] pool is not responding, closing connections
[1420777422][warning][pxy87488] closing proxy
[1420777424][debug][proxy] removing proxy 140625070906960
Traceback (most recent call last):
  File "strelay.py", line 139, in <module>
    pool = pool_connection.connect()
  File "/home/apache/connection.py", line 20, in connect
    self.conn.connect((self.ip, self.port))
socket.error: [Errno 110] Connection timed out

at long a connection with the pool close with an error

**Comment by p4u** [comment]
It looks like a remote pool problem. Can you post the command line used to launch the relay?
